### PR TITLE
- added constants for http status codes

### PR DESCRIPTION
**Pull request by LegendOfGIT**
- added constants for http status codes

### CODE REVIEW

**Comment by LegendOfGIT** [comment]
The class Response will be removed soon?
What is the future concept of this package?

**Comment by Nyholm** [comment]
We would like to be compatible with psr7. So this client would be compatible with any psr7 implementation

**Comment by LegendOfGIT** [comment]
When will the master fullfill psr7 standards?

**Comment by LegendOfGIT** [comment]
I would be great if you merge my pull request.
It does not really matter if the class Response will be dropped in the future, since developers still using older versions of this package.

If it will be dropped, it will be dropped.
Til then, it won't hurt adding this constants ;)

**Comment by Nyholm** [comment]
Ill try to put in some work on buzz during next week.

**Comment by LegendOfGIT** [comment]
Very nice.
Thank you in advance :)

**Comment by Nyholm** [comment]
Thank you for this. I do not see the harm in merging this. 

But FYI: This class will be removed within near future.

**Pull request merged**
