### PR TITLE
Expose curl information

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by Nyholm** [comment]
I like this feature, I really like the simple implementation. 
I've been looking at this PR 5 times now. I wish to make this feature opt-in. Do you have a suggestion how we can make it so?

**Comment by Nyholm** [comment]
I was considering adding this in a Plugin or enable via configuration options.

**Comment by lyrixx** [comment]
Here we go, a new option has been added

**Comment by lyrixx** [comment]
No problem 
Thanks for merging

**Pull request merged**
