### PR TITLE
Add symfony/options-resolver ^7.0 to composer

### PR DESCRIPTION
**Pull request by sunkan**

### CODE REVIEW

**Comment by kabudu** [comment]
Any chance this PR can be merged? @kriswallsmith

**Comment by icarus94** [comment]
Hi, are there any plans to create a release tag with these changes?

**Comment by sunkan** [comment]
@Nyholm Hi, are there any plans to create a release tag with these changes?

**Comment by Nyholm** [comment]
Sure. Lets!

**Comment by kriswallsmith** [comment]
Thanks @Nyholm!

**Pull request merged**
