### PR TITLE
Allow installation of `symfony/options-resolver:^5.0`

### LINKED ISSUE #405: Update composer.json for latest version of symfony/options-resolver
symfony/options-resolver is now on Version 5, which is installed by default in Laravel 6 projects.

Would it please be possible to update the composer json file accordingly.

```
"symfony/options-resolver": "^3.4 || ^4.0 || ^5",
```

### PR DESCRIPTION
**Pull request by jdreesen**
Fixes #405

### CODE REVIEW

**Comment by jdreesen** [comment]
PHPStan errors on Travis are unrelated.

**Comment by webhdx** [comment]
@kriswallsmith Can we proceed with this one? We are migrating ezsystems/ezplatform to Symfony 5 and your package is blocking us. We don't really want to maintain our own fork. Thanks in advance!

**Comment by Nyholm** [comment]
There are no changes in the option resolver between 4 and 5. Thank you for this PR. 

I'll make the build green and release a new version this week.

**Comment by someniatko** [comment]
> I'll make the build green and release a new version this week.

@Nyholm Hi, i guess it's already the time for releasing a new version.

**Comment by Nyholm** [comment]
Thank you for the ping. 

Here you go: https://github.com/kriswallsmith/Buzz/releases/tag/1.2.1

**Pull request merged**
