### PR TITLE
Exclude non-essential files in .gitattributes

### PR DESCRIPTION
**Pull request by vinkla**
[Exclude non-essential files in .gitattributes.](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production)

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you Vincent. 

I see your name showing up on more an more projects lately. 👍

**Comment by vinkla** [comment]
@Nyholm I follow you on GitHub and Twitter. That is probably why 😄

**Comment by staabm** [comment]
@Nyholm could you create a new release including this change? atm the latest release contains test/server.php which allows to passin a SLEEP timeout via GET parameter.

usually the vendor files should not be public accesible,... but sometimes it is and this renders a DOS vector in this situations ;).

**Comment by Nyholm** [comment]
Yes. Sure. I will work a lot with this library for the rest of the year. I will put in some work this weekend.

**Comment by Nyholm** [comment]
Fixed.

**Comment by staabm** [comment]
Thanks!

**Pull request merged**
