### PR TITLE
Improve __construct $responseFactory use ResponseFactoryInterface type

### PR DESCRIPTION
**Pull request by kids-return**
Improve __construct $responseFactory use ResponseFactoryInterface type

### CODE REVIEW

**Comment by kids-return** [comment]
di support

**Comment by sunkan** [comment]
Hi

Did you test this code?

1. It breaks the tests
2. The code you have written will always throw a `InvalidArgumentException` unless the response factory implements both `ResponseFactoryInterface` and `ResponseFactory `
3. And this would require a major version bump

**Comment by kids-return** [comment]
Thank you very much for your answer.
ResponseFactory is an interface， that will cause BC 🤔
Is there an improvement plan, or based entirely on Psr 😔

**Comment by Nyholm** [comment]
You still can use `ResponseFactoryInterface`, right?

This PR is just about removing functionality. Why should we not allow HTTPlug factories? What is the benefit?

**Pull request closed without merging**
