### PR TITLE
Added support for max_filesize

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 

I like this feature and I think it is something we should support. However, I dont like that we add more configuration options. 

The idea of buzz is to be as small and simple as possible. If you really need out of the box support for max_filesize, then maybe Guzzle is the library you should use. Especially for options not used by 60% of the users. 

I suggest you revert the changes in AbstractCurl but you keep everything related to CallbackException. Then you can still achieve the same result but with more code in your app. What do you think about that?

**Comment by lyrixx** [comment]
Hmm. At first I thought about implementing this in my code.
But I said to myself: let's contribute. The patch is quite small, and it could help someone else.

I **really** don't want to use guzzle. It became so complicated / complex / over-engineered. Buzz is a really cool lib!

As the patch is really small, is it an issue to have it in the core? You already support `timeout`. IMHO, this deserves to be in the core.

**Comment by Nyholm** [comment]
Im happy you contributed. Thank you

> I really don't want to use guzzle. It became so complicated / complex / over-engineered. Buzz is a really cool lib!

And that is part of a reason why Buzz should be minimal. 

> As the patch is really small, is it an issue to have it in the core? You already support timeout. IMHO, this deserves to be in the core.

The few options we currently have are chosen carefully. I dont think a `max_filesize` option will be used by more that 3% of the users. 

I think the CallbackException is good and I think the anonymous function should be added to the docs.

**Comment by lyrixx** [comment]
Failures are not related. I tried to fixed it, but heu ...

**Comment by Nyholm** [comment]
Yeah, I see that. 

Thanks for trying.

**Pull request merged**
