### PR TITLE
Fixed wrong check for uploaded file.

### PR DESCRIPTION
**Pull request by tacconthommy**
When trying to upload a file, you got a 500 `Object of class Symfony\Component\HttpFoundation\File\UploadedFile could not be converted to boolean`. This should fix it.

### CODE REVIEW

**Comment by ptatoud** [comment]
Hi @kriswallsmith !
I've the same error than @tacconthommy.  I 've just write 
`$pj1 = new FormUpload($pj1);` and `$pj1` is an `Symfony\Component\HttpFoundation\File\UploadedFile`.

Is it possible to merge this fix ?
Thx

**Comment by ptatoud** [comment]
@kriswallsmith : Any chance to get this merged in ?

**Comment by kriswallsmith** [comment]
If someone can add a test I will look at this. I'm not sure how to reproduce.

**Comment by ptatoud** [comment]
@kriswallsmith, i can write a test but you can't instanciate and verify a var in if.
In fact, it's easier to detect an error (for exemple "=" instead of "==") in a condition.

In this case, if `$value->getFile()` is not a file but not empty, your condition will always be true but should not :)

**Comment by Nyholm** [comment]
Closing because of inactivity.

**Pull request closed without merging**
